-- SPARK PostgreSQL schema
-- Run this against the mywebsite database:
-- psql -h localhost -p 5432 -U postgres -d mywebsite -f schema.sql

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    student_id VARCHAR(50) UNIQUE,
    full_name VARCHAR(150),
    email VARCHAR(150),
    phone VARCHAR(30),
    grade VARCHAR(20),
    date_of_birth VARCHAR(30),
    department VARCHAR(150),
    subjects TEXT,
    target_degree TEXT,
    career_interest TEXT,
    why_interest TEXT,
    strengths TEXT,
    academic_average REAL DEFAULT 0,
    readiness_score REAL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS academics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER REFERENCES students(id),
    subject VARCHAR(100),
    marks REAL,
    grade VARCHAR(30),
    exam_name VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS activities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER REFERENCES students(id),
    activity_name VARCHAR(200),
    category VARCHAR(100),
    description TEXT,
    achievement TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS universities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER REFERENCES students(id),
    university_name VARCHAR(200),
    country VARCHAR(100),
    degree VARCHAR(200),
    application_type VARCHAR(100),
    deadline VARCHAR(30),
    status VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER REFERENCES students(id),
    document_name VARCHAR(200),
    file_name VARCHAR(255),
    file_path VARCHAR(500),
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS test_scores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    test_name VARCHAR(100) NOT NULL,
    score VARCHAR(50),
    test_date VARCHAR(30),
    status VARCHAR(30) DEFAULT 'Planned',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS milestones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    title VARCHAR(200) NOT NULL,
    target_date VARCHAR(30),
    status VARCHAR(50) DEFAULT 'Not Started',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS essays (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    essay_prompt TEXT NOT NULL,
    university VARCHAR(200),
    draft_status VARCHAR(50) DEFAULT 'Uploaded for Counselor Review',
    deadline VARCHAR(30),
    file_path VARCHAR(500),
    file_name VARCHAR(255),
    feedback TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recommenders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    teacher_name VARCHAR(150) NOT NULL,
    subject VARCHAR(100),
    university VARCHAR(200),
    deadline VARCHAR(30),
    brag_sheet TEXT,
    status VARCHAR(50) DEFAULT 'Requested',
    lor_file_path VARCHAR(500),
    lor_file_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deadlines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    action VARCHAR(250) NOT NULL,
    due_date VARCHAR(30),
    category VARCHAR(100),
    status VARCHAR(50) DEFAULT 'Pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prerequisites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    requirement VARCHAR(200) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS readiness_checklist (
    student_id INTEGER NOT NULL REFERENCES students(id),
    item_key VARCHAR(150) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (student_id, item_key)
);

CREATE TABLE IF NOT EXISTS master_universities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) UNIQUE NOT NULL,
    country VARCHAR(100) NOT NULL,
    best_fit_courses TEXT,
    academic_requirement TEXT,
    key_subjects TEXT,
    tests TEXT,
    competitive_target TEXT,
    application_deadline TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS master_university_requirements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id INTEGER NOT NULL REFERENCES master_universities(id),
    requirement_name VARCHAR(200) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS student_prerequisites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    university_id INTEGER NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
    requirement_name VARCHAR(200) NOT NULL,
    category VARCHAR(50),
    description TEXT,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    completed_at VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    deadline_id INTEGER,
    item_type VARCHAR(50),
    severity VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    target_url VARCHAR(200),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS counselor_notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER REFERENCES students(id),
    counselor_id INTEGER REFERENCES users(id),
    note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_students_user_id ON students(user_id);
CREATE INDEX IF NOT EXISTS idx_academics_student_id ON academics(student_id);
CREATE INDEX IF NOT EXISTS idx_activities_student_id ON activities(student_id);
CREATE INDEX IF NOT EXISTS idx_universities_student_id ON universities(student_id);
CREATE INDEX IF NOT EXISTS idx_documents_student_id ON documents(student_id);
CREATE INDEX IF NOT EXISTS idx_student_prerequisites_student_id ON student_prerequisites(student_id);
CREATE INDEX IF NOT EXISTS idx_alerts_student_id ON alerts(student_id);

-- The Flask startup seeds the default users and master university data.
